import Link from 'next/link';
import { Logo } from '@/components/Logo';

export const metadata = {
  title: 'Imprint - VibeM',
  description: 'Legal notice for VibeM',
};

export default function Imprint() {
  return (
    <div className="min-h-screen">
      {/* Navigation */}
      <nav className="border-b border-[var(--border)] bg-[var(--bg)]">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3">
            <Logo size={36} />
            <span className="font-bold text-xl text-[var(--text-strong)]">VibeM</span>
          </Link>
          <Link href="/" className="text-sm text-[var(--text-muted)] hover:text-[var(--primary)]">
            ← Back to Home
          </Link>
        </div>
      </nav>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold text-[var(--text-strong)] mb-8">Imprint</h1>
        
        <div className="prose prose-gray max-w-none">
          <p className="text-[var(--text-muted)] mb-8">
            Legal Notice according to § 5 ECG (Austrian E-Commerce Act)
          </p>

          <h2 className="text-xl font-semibold text-[var(--text-strong)] mt-8 mb-4">Company Information</h2>
          <p className="text-[var(--text)] mb-4">
            S&C Holding GmbH<br />
            Halbgasse 1a<br />
            1070 Vienna, Austria
          </p>
          <p className="text-[var(--text)] mb-4">
            Brand: VibeM<br />
            Website: <a href="https://www.vibem.net" className="text-[var(--primary)] hover:underline">www.vibem.net</a><br />
            Email: <a href="mailto:info@vibem.net" className="text-[var(--primary)] hover:underline">info@vibem.net</a><br />
            VAT ID: ATU70341613
          </p>

          <h2 className="text-xl font-semibold text-[var(--text-strong)] mt-8 mb-4">Management</h2>
          <p className="text-[var(--text)] mb-4">
            Managing Director: Mag. Markus Höfinger
          </p>

          <h2 className="text-xl font-semibold text-[var(--text-strong)] mt-8 mb-4">Regulatory Authority</h2>
          <p className="text-[var(--text)] mb-4">
            Magistratisches Bezirksamt des 7. Bezirkes, Vienna
          </p>

          <h2 className="text-xl font-semibold text-[var(--text-strong)] mt-8 mb-4">Applicable Law</h2>
          <p className="text-[var(--text)] mb-4">
            Information pursuant to § 5 Austrian E-Commerce Act (ECG)
          </p>

          <h2 className="text-xl font-semibold text-[var(--text-strong)] mt-8 mb-4">Media Disclosure</h2>
          <p className="text-[var(--text)] mb-4">
            Disclosure according to § 25 Austrian Media Act (Mediengesetz)<br />
            Media Owner: S&C Holding GmbH<br />
            Registered Office: Vienna, Austria<br />
            Business Purpose: Web Services
          </p>

          <h2 className="text-xl font-semibold text-[var(--text-strong)] mt-8 mb-4">Copyright Notice</h2>
          <p className="text-[var(--text)] mb-4">
            Accessing, copying, saving, and modifying the website, its content, or results generated by the display tools, 
            in whole or in part, is permitted solely for private, non-commercial use. Copyright notices and trademark 
            designations may not be altered or removed.
          </p>
          <p className="text-[var(--text)] mb-4">
            All other actions require prior written permission from the website owner. Access to the provided information 
            must not impair the use of the site for other visitors.
          </p>
          <p className="text-[var(--text)] mb-4">
            The creation of hyperlinks or inline links from other websites to pages of this website without prior written 
            consent is expressly prohibited. In particular, it is not permitted to embed or display web pages or their 
            content via hyperlinks in a frame.
          </p>

          <h2 className="text-xl font-semibold text-[var(--text-strong)] mt-8 mb-4">External Links</h2>
          <p className="text-[var(--text)] mb-4">
            S&C Holding GmbH expressly distances itself from all content of all externally linked pages on this website 
            and does not adopt this content as its own. This declaration applies to all external links on vibem.net.
          </p>

          <h2 className="text-xl font-semibold text-[var(--text-strong)] mt-8 mb-4">Data Protection</h2>
          <p className="text-[var(--text)] mb-4">
            Your personal data is treated with great care and is not shared with third parties except as described in our{' '}
            <Link href="/legal/privacy" className="text-[var(--primary)] hover:underline">Privacy Policy</Link>.
          </p>
        </div>
      </main>

      {/* Footer */}
      <footer className="py-8 px-6 border-t border-[var(--border)]">
        <div className="max-w-3xl mx-auto text-center text-sm text-[var(--text-muted)]">
          © {new Date().getFullYear()} S&C Holding GmbH. All rights reserved.
        </div>
      </footer>
    </div>
  );
}
